In [4]:
import numpy as np
import pandas as pd
import math

In [1]:
"""Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?"""

'Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?'

In [7]:
"""Risposta: La lista di liste rappresenta un'array."""



"Risposta: La lista di liste rappresenta un'array."

In [12]:
"""Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?"""

'Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?'

In [14]:
x = math.sin(15)
print(x)

0.6502878401571168


In [15]:
y = math.cos(32)
print(y)

0.8342233605065102


In [16]:
a = math.factorial(56)
print(a)

710998587804863451854045647463724949736497978881168458687447040000000000000


In [18]:
b = math.pi
print(b)

3.141592653589793


In [19]:
"""Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare help(math.degrees)"""

'Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare help(math.degrees)'

In [20]:
c = math.degrees(math.pi)
print(c)

180.0


In [21]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [22]:
"""L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] trasformiamola in un array NumPy (casting): lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA: • qual è stata la vendita massima mensile? E quella minima? • quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? • quali sono le vendite minori di 3000 oggetti? • in media quanti oggetti sono stati venduti al mese?"""

"L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] trasformiamola in un array NumPy (casting): lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA: • qual è stata la vendita massima mensile? E quella minima? • quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? • quali sono le vendite minori di 3000 oggetti? • in media quanti oggetti sono stati venduti al mese?"

In [23]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 

In [24]:
lst = np.array(lst)

In [26]:
print(lst.max())

8150


In [27]:
print(lst.min())

1280


In [28]:
print(lst.mean())

4634.166666666667


In [30]:
filter = lst[lst>4999]
print(filter)

[5500 7200 6410 8150 7100 5350]


In [31]:
filter2 = lst[lst<3000]
print(filter2)

[2000 1280 1900 2500]


In [36]:
"""L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: import numpy as np stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) L'azienda ci chiede di raddoppiare tutti gli stipendi"""

"L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray: import numpy as np stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) L'azienda ci chiede di raddoppiare tutti gli stipendi"

In [33]:
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 

In [34]:
print(stipendi)

[ 100  200  300  400  500  600  700  800  900 1000]


In [35]:
lista_stipendi_raddoppiati = []
lista_stipendi_raddoppiati_com = []
print(stipendi[1])
for stipendio in stipendi:
    lista_stipendi_raddoppiati.append(stipendio*2)
print("Lista stipendi raddoppiati", lista_stipendi_raddoppiati)

200
Lista stipendi raddoppiati [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
